In [35]:
import numpy as np
import csv
import pandas as pd

In [36]:
# Definindo a função sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivada da função sigmoid
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Função de perda (Erro quadrático médio)
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

In [37]:
# Carregar dados do CSV
"""
data = []
with open('../model/data/modis_2023_Brazil.csv', 'r', encoding='utf-8') as ficheiro:
    reader = csv.reader(ficheiro)
    next(reader)  # Pula o cabeçalho
    for linha in reader:
        # Converte as colunas para float e armazena como tuplas de latitude e longitude
        data.append((float(linha[0]), float(linha[1])))
"""

# Supondo que arq_combined já está definido e contém dados combinados
arq2022 = pd.read_csv('../model/data/modis_2022_Brazil.csv', usecols=['latitude', 'longitude'])
arq2023 = pd.read_csv('../model/data/modis_2023_Brazil.csv', usecols=['latitude', 'longitude'])
arq_combined = pd.concat([arq2022, arq2023])

In [38]:
X = []
y = []

# Ajustando para o tamanho do conjunto de dados disponível
for i in range(len(arq_combined) - 3):
    X.append(np.array(arq_combined[i:i+3]).flatten())  # Achata a sequência em um vetor 1D
    
    # Prever os próximos pares futuros (até onde os dados permitem)
    future_points = np.array(arq_combined[i+3:min(i+8, len(arq_combined))]).flatten()
    
    # Se não houver pares suficientes, preencher com zeros
    if len(future_points) < 10:
        future_points = np.pad(future_points, (0, 10 - len(future_points)), mode='constant')
    
    y.append(future_points)

X = np.array(X)
y = np.array(y)

print(f"X: {X}")
print(f"y: {y}")

X: [[-23.1626 -53.7109 -23.3932 -53.8741 -23.3858 -53.8703]
 [-23.3932 -53.8741 -23.3858 -53.8703 -20.237  -56.6381]
 [-23.3858 -53.8703 -20.237  -56.6381 -20.2169 -56.6297]
 ...
 [ -6.8139 -38.3349  -6.7159 -38.0333  -6.7172 -38.0423]
 [ -6.7159 -38.0333  -6.7172 -38.0423  -6.639  -37.816 ]
 [ -6.7172 -38.0423  -6.639  -37.816   -6.5795 -38.1112]]
y: [[-20.237  -56.6381 -20.2169 ... -56.6447 -18.4374 -55.525 ]
 [-20.2169 -56.6297 -20.2252 ... -55.525  -20.2401 -56.6554]
 [-20.2252 -56.6405 -20.2317 ... -56.6554 -20.222  -56.6232]
 ...
 [ -6.639  -37.816   -6.5795 ...   0.       0.       0.    ]
 [ -6.5795 -38.1112  -6.5694 ...   0.       0.       0.    ]
 [ -6.5694 -38.1677   0.     ...   0.       0.       0.    ]]


In [39]:
X = []
y = []

# Ajustando para o tamanho do conjunto de dados disponível
for i in range(len(arq_combined) - 3):
    X.append(np.array(arq_combined[i:i+3]).flatten())  # Achata a sequência em um vetor 1D
    
    # Prever os próximos pares futuros (até onde os dados permitem)
    future_points = np.array(arq_combined[i+3:min(i+8, len(arq_combined))]).flatten()
    
    # Se não houver pares suficientes, preencher com zeros
    if len(future_points) < 10:
        future_points = np.pad(future_points, (0, 10 - len(future_points)), mode='constant')
    
    y.append(future_points)

X = np.array(X)
y = np.array(y)

print(f"X: {X}")
print(f"y: {y}")

X: [[-23.1626 -53.7109 -23.3932 -53.8741 -23.3858 -53.8703]
 [-23.3932 -53.8741 -23.3858 -53.8703 -20.237  -56.6381]
 [-23.3858 -53.8703 -20.237  -56.6381 -20.2169 -56.6297]
 ...
 [ -6.8139 -38.3349  -6.7159 -38.0333  -6.7172 -38.0423]
 [ -6.7159 -38.0333  -6.7172 -38.0423  -6.639  -37.816 ]
 [ -6.7172 -38.0423  -6.639  -37.816   -6.5795 -38.1112]]
y: [[-20.237  -56.6381 -20.2169 ... -56.6447 -18.4374 -55.525 ]
 [-20.2169 -56.6297 -20.2252 ... -55.525  -20.2401 -56.6554]
 [-20.2252 -56.6405 -20.2317 ... -56.6554 -20.222  -56.6232]
 ...
 [ -6.639  -37.816   -6.5795 ...   0.       0.       0.    ]
 [ -6.5795 -38.1112  -6.5694 ...   0.       0.       0.    ]
 [ -6.5694 -38.1677   0.     ...   0.       0.       0.    ]]


In [40]:
X = []
y = []

# Ajustando para o tamanho do conjunto de dados disponível
for i in range(len(arq_combined) - 3):
    X.append(np.array(arq_combined[i:i+3]).flatten())  # Achata a sequência em um vetor 1D
    
    # Prever os próximos pares futuros (até onde os dados permitem)
    future_points = np.array(arq_combined[i+3:min(i+8, len(arq_combined))]).flatten()
    
    # Se não houver pares suficientes, preencher com zeros
    if len(future_points) < 10:
        future_points = np.pad(future_points, (0, 10 - len(future_points)), mode='constant')
    
    y.append(future_points)

X = np.array(X)
y = np.array(y)

print(f"X: {X}")
print(f"y: {y}")

X: [[-23.1626 -53.7109 -23.3932 -53.8741 -23.3858 -53.8703]
 [-23.3932 -53.8741 -23.3858 -53.8703 -20.237  -56.6381]
 [-23.3858 -53.8703 -20.237  -56.6381 -20.2169 -56.6297]
 ...
 [ -6.8139 -38.3349  -6.7159 -38.0333  -6.7172 -38.0423]
 [ -6.7159 -38.0333  -6.7172 -38.0423  -6.639  -37.816 ]
 [ -6.7172 -38.0423  -6.639  -37.816   -6.5795 -38.1112]]
y: [[-20.237  -56.6381 -20.2169 ... -56.6447 -18.4374 -55.525 ]
 [-20.2169 -56.6297 -20.2252 ... -55.525  -20.2401 -56.6554]
 [-20.2252 -56.6405 -20.2317 ... -56.6554 -20.222  -56.6232]
 ...
 [ -6.639  -37.816   -6.5795 ...   0.       0.       0.    ]
 [ -6.5795 -38.1112  -6.5694 ...   0.       0.       0.    ]
 [ -6.5694 -38.1677   0.     ...   0.       0.       0.    ]]


In [41]:
# Preparação dos dados para treinamento
X = []
y = []

for i in range(len(arq_combined) - 3):
    X.append(np.array(arq_combined[i:i+3]).flatten())  # Usando os 3 pares passados
    future_points = np.array(arq_combined[i+3:min(i+8, len(arq_combined))]).flatten()
    if len(future_points) < 10:  # Preencher com zeros se faltar dados
        future_points = np.pad(future_points, (0, 10 - len(future_points)), mode='constant')
    y.append(future_points)

X = np.array(X)
y = np.array(y)

# Certificar que as dimensões de X e y são compatíveis
assert X.shape[0] == y.shape[0], "As dimensões de X e y não coincidem."


In [42]:
# Definindo as dimensões da rede neural
input_size = X.shape[1]
hidden_size = 10  # Número de neurônios na camada oculta
output_size = y.shape[1]

# Inicializar pesos e biases
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Forward propagation
def forward(X):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    y_pred = sigmoid(z2)
    return y_pred, a1

In [43]:
# Treinamento (Backpropagation)
learning_rate = 0.01
for epoch in range(1000):
    y_pred, a1 = forward(X)
    loss = mse_loss(y, y_pred)
    
    dL_dy_pred = -2 * (y - y_pred) / len(y)
    
    # Gradientes
    dL_dW2 = np.dot(a1.T, dL_dy_pred)
    dL_db2 = np.sum(dL_dy_pred, axis=0)
    dL_da1 = np.dot(dL_dy_pred, W2.T) * sigmoid_derivative(a1)
    dL_dW1 = np.dot(X.T, dL_da1)
    dL_db1 = np.sum(dL_da1, axis=0)
    
    # Atualização de pesos e biases
    W2 -= learning_rate * dL_dW2
    b2 -= learning_rate * dL_db2
    W1 -= learning_rate * dL_dW1
    b1 -= learning_rate * dL_db1
    
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

Epoch 0, Loss: 1508.5532357215232


/var/folders/34/gby6tkr103xfh0fy_017m5grcjxgrv/T/ipykernel_3869/2582420000.py:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


Epoch 100, Loss: 1477.4546431774695
Epoch 200, Loss: 1477.4546431774695
Epoch 300, Loss: 1477.4546431774695
Epoch 400, Loss: 1477.4546431774695
Epoch 500, Loss: 1477.4546431774695
Epoch 600, Loss: 1477.4546431774695
Epoch 700, Loss: 1477.4546431774695
Epoch 800, Loss: 1477.4546431774695
Epoch 900, Loss: 1477.4546431774695


In [44]:
# Limites para latitude e longitude
# Aqui preciso colocar o limite do Brasil
# Evitar para que caia na água 
latitude_min, latitude_max = -22.9068, 0.80700 # altura do Brasil 
longitude_min, longitude_max = -34.79389, -73.99222 # Largura do Brasil

In [45]:
# Previsão de novos pares de coordenadas
if len(arq_combined) >= 3:
    new_sequence = np.array(arq_combined[-3:]).flatten()
    predicted_values, _ = forward(new_sequence)

    predictions = predicted_values.reshape(-1, 2)

    print("Next predicted latitudes and longitudes:")
    for i, pred in enumerate(predictions):
        latitude, longitude = pred
        # Limitar aos limites definidos
        latitude = np.clip(latitude, latitude_min, latitude_max)
        longitude = np.clip(longitude, longitude_min, longitude_max)
        print(f"Prediction {i + 1}: Latitude: {latitude}, Longitude: {longitude}")

Next predicted latitudes and longitudes:
Prediction 1: Latitude: 0.0, Longitude: -73.99222
Prediction 2: Latitude: 0.0, Longitude: -73.99222
Prediction 3: Latitude: 0.0, Longitude: -73.99222
Prediction 4: Latitude: 0.0, Longitude: -73.99222
Prediction 5: Latitude: 0.0, Longitude: -73.99222


/var/folders/34/gby6tkr103xfh0fy_017m5grcjxgrv/T/ipykernel_3869/2582420000.py:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
